# Generated by Django 3.2.6 on 2021-08-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'pad',
            },
        ),
    ]
