# Generated by Django 3.2.6 on 2021-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField()),
            ],
            options={
                'db_table': 'pad_table',
            },
        ),
    ]
