# Generated by Django 3.2.6 on 2021-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
