# Generated by Django 3.2.6 on 2021-08-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('enName', models.CharField(max_length=20)),
                ('sideEffect', models.TextField()),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection', models.FloatField()),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saengae_server.ingredient')),
                ('pad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saengae_server.pad')),
            ],
            options={
                'db_table': 'detection',
            },
        ),
        migrations.AddField(
            model_name='pad',
            name='ingredients',
            field=models.ManyToManyField(through='Saengae_server.Detection', to='Saengae_server.Ingredient'),
        ),
    ]
