# Generated by Django 3.2.6 on 2021-08-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='ingredient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Saengae_server.ingredient'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Saengae_server.pad'),
        ),
    ]
