# Generated by Django 3.2.6 on 2021-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='safeScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
