# Generated by Django 3.2.6 on 2021-08-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pad',
            table='pad',
        ),
    ]
