# Generated by Django 3.2.6 on 2021-08-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0002_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pad',
            options={'ordering': ['rank']},
        ),
    ]
