# Generated by Django 3.2.6 on 2021-08-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saengae_server', '0002_alter_pad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pad',
            options={'managed': False},
        ),
    ]
